//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInvoice
    {
        public int InvoiceId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double SubTotal { get; set; }
        public double TotalWithTax { get; set; }
        public string CreditCardType { get; set; }
        public string CardNumber { get; set; }
        public string VendorUserName { get; set; }
        public string EmployeeUserName { get; set; }
    }
}
