//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeText
    {
        public int TextId { get; set; }
        public string TextBody { get; set; }
        public string ReceiverUserName { get; set; }
        public string SenderUserName { get; set; }
    }
}
