//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierLog
    {
        public int LogId { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Comment { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual SupplierSchedule SupplierSchedule { get; set; }
    }
}
