//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportLog
    {
        public int LogId { get; set; }
        public string RequestSubject { get; set; }
        public string RequestBody { get; set; }
        public string SenderUserName { get; set; }
        public string UserType { get; set; }
        public System.DateTime Date { get; set; }
        public string SupportUserName { get; set; }
    }
}
